# Generated by Django 5.0.1 on 2024-01-22 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('author', models.CharField(blank=True, max_length=100, null=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('source_name', models.CharField(blank=True, max_length=100, null=True)),
                ('url', models.URLField(blank=True, max_length=255, null=True)),
                ('image_url', models.URLField(blank=True, max_length=255, null=True)),
                ('category', models.CharField(blank=True, max_length=50, null=True)),
                ('country', models.CharField(blank=True, max_length=50, null=True)),
                ('source', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
