# Generated by Django 5.0.1 on 2024-01-26 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news_api', '0003_alter_news_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='image_url',
            new_name='urlToImage',
        ),
        migrations.RemoveField(
            model_name='news',
            name='category',
        ),
        migrations.RemoveField(
            model_name='news',
            name='country',
        ),
        migrations.RemoveField(
            model_name='news',
            name='source',
        ),
        migrations.RemoveField(
            model_name='news',
            name='source_name',
        ),
    ]
